parameters:
#    makin_mind_project.example.class: MakinMind\ProjectBundle\Example

services:
#    makin_mind_project.example:
#        class: %makin_mind_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
