EditorBundle_editorTree:
    pattern:  /editorTree/{id}
    defaults: { _controller: MakinMindEditorBundle:Editor:treeManager }
    requirements:
        id: \d+

EditorBundle_editor:
    pattern:  /editor/{id}
    defaults: { _controller: MakinMindEditorBundle:Editor:editor }
    requirements:
        _method: GET
        id: \d+
    options:
        expose: true

EditorBundle_structManage:
    pattern: /structManager
    defaults: {_controller: MakinMindEditorBundle:Editor:manageStructure}
    options:
        expose: true