parameters:
#    makin_mind_editor.example.class: MakinMind\EditorBundle\Example

services:
#    makin_mind_editor.example:
#        class: %makin_mind_editor.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
