parameters:
#    makin_mind_portal.example.class: MakinMind\PortalBundle\Example

services:
#    makin_mind_portal.example:
#        class: %makin_mind_portal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
