parameters:
#    makin_mind_resource.example.class: MakinMind\ResourceBundle\Example

services:
#    makin_mind_resource.example:
#        class: %makin_mind_resource.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
